import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:uuid/uuid.dart'; // For generating unique IDs
import 'dart:math'; // For min/max functions

// Import firebase_options.dart (generated by FlutterFire CLI)
import 'firebase_options.dart';

final Uuid uuid = Uuid(); // Instantiate Uuid once

// --- Data Models ---

class SolarPanel {
  String id;
  String modelName;
  double lengthM;
  double widthM;
  int wattageW;
  bool isFaulty;
  DateTime addedTimestamp;

  SolarPanel({
    required this.id,
    required this.modelName,
    required this.lengthM,
    required this.widthM,
    required this.wattageW,
    this.isFaulty = false,
    required this.addedTimestamp,
  });

  double get areaM2 => lengthM * widthM;

  Map<String, dynamic> toJson() => {
        'id': id,
        'modelName': modelName,
        'lengthM': lengthM,
        'widthM': widthM,
        'wattageW': wattageW,
        'isFaulty': isFaulty,
        'addedTimestamp': addedTimestamp.toIso8601String(),
      };

  factory SolarPanel.fromJson(Map<String, dynamic> json) {
    return SolarPanel(
      id: json['id'] as String,
      modelName: json['modelName'] as String,
      lengthM: (json['lengthM'] as num).toDouble(),
      widthM: (json['widthM'] as num).toDouble(),
      wattageW: (json['wattageW'] as num).toInt(),
      isFaulty: json['isFaulty'] as bool? ?? false,
      addedTimestamp: DateTime.parse(json['addedTimestamp'] as String),
    );
  }
}

class RooftopSection {
  String id;
  String name;
  double roofLengthM;
  double roofWidthM;
  Map<String, SolarPanel> panels;

  RooftopSection({
    required this.id,
    required this.name,
    required this.roofLengthM,
    required this.roofWidthM,
    Map<String, SolarPanel>? panels,
  }) : this.panels = panels ?? {};

  double get totalAreaM2 => roofLengthM * roofWidthM;

  double get usedAreaM2 {
    return panels.values.fold(0.0, (sum, panel) => sum + panel.areaM2);
  }

  double get remainingAreaM2 => max(0, totalAreaM2 - usedAreaM2);

  int get totalWattageW {
    return panels.values.fold(0, (sum, panel) => sum + panel.wattageW);
  }

  int get activeWattageW {
    return panels.values
        .where((p) => !p.isFaulty)
        .fold(0, (sum, panel) => sum + panel.wattageW);
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'roofLengthM': roofLengthM,
        'roofWidthM': roofWidthM,
        'panels': panels.map((key, value) => MapEntry(key, value.toJson())),
      };

  factory RooftopSection.fromJson(Map<String, dynamic> json) {
    final panelData = json['panels'] as Map<dynamic, dynamic>?;
    final Map<String, SolarPanel> parsedPanels = {};
    if (panelData != null) {
      panelData.forEach((key, value) {
        if (key is String && value is Map) {
          parsedPanels[key] =
              SolarPanel.fromJson(value.cast<String, dynamic>());
        }
      });
    }
    return RooftopSection(
      id: json['id'] as String,
      name: json['name'] as String,
      roofLengthM: (json['roofLengthM'] as num).toDouble(),
      roofWidthM: (json['roofWidthM'] as num).toDouble(),
      panels: parsedPanels,
    );
  }
}

// --- Main Application ---

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(SolarMitraSimulationApp());
}

class SolarMitraSimulationApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SolarMitra Panel Simulator',
      theme: ThemeData(
          primarySwatch: Colors.green,
          visualDensity: VisualDensity.adaptivePlatformDensity,
          useMaterial3: true, // Optional: for Material 3 styling
          inputDecorationTheme: InputDecorationTheme(
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8.0),
            ),
          ),
          elevatedButtonTheme: ElevatedButtonThemeData(
              style: ElevatedButton.styleFrom(
                  padding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8.0))))),
      home: RooftopManagementScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}

// --- Rooftop Management Screen ---

class RooftopManagementScreen extends StatefulWidget {
  @override
  _RooftopManagementScreenState createState() =>
      _RooftopManagementScreenState();
}

class _RooftopManagementScreenState extends State<RooftopManagementScreen> {
  // Firebase Realtime Database reference
  // Assumes data is stored per installation/user. For simplicity, using a common root.
  final DatabaseReference _dbRef = FirebaseDatabase.instance
      .ref("solar_system_sim/install_01/rooftopSections");

  String? _selectedRooftopId;
  Map<String, RooftopSection> _rooftopSections = {};

  @override
  void initState() {
    super.initState();
    _listenToRooftopSections();
  }

  void _listenToRooftopSections() {
    _dbRef.onValue.listen((DatabaseEvent event) {
      final Map<String, RooftopSection> loadedSections = {};
      if (event.snapshot.exists && event.snapshot.value != null) {
        final data = event.snapshot.value as Map<dynamic, dynamic>;
        data.forEach((key, value) {
          if (key is String && value is Map) {
            loadedSections[key] =
                RooftopSection.fromJson(value.cast<String, dynamic>());
          }
        });
      }
      setState(() {
        _rooftopSections = loadedSections;
        // If the currently selected rooftop was deleted elsewhere, deselect it.
        if (_selectedRooftopId != null &&
            !_rooftopSections.containsKey(_selectedRooftopId)) {
          _selectedRooftopId = null;
        }
        // If no rooftop is selected and there are rooftops available, select the first one.
        if (_selectedRooftopId == null && _rooftopSections.isNotEmpty) {
          _selectedRooftopId = _rooftopSections.keys.first;
        }
      });
    }, onError: (error) {
      // Handle Firebase read errors
      print("Firebase error: $error");
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
              content: Text("Error loading data from Firebase: $error"),
              backgroundColor: Colors.red),
        );
      }
    });
  }

  void _addRooftopSectionDialog() {
    final nameController = TextEditingController();
    final lengthController = TextEditingController();
    final widthController = TextEditingController();
    final formKey = GlobalKey<FormState>();

    showDialog(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: Text("Add Rooftop Section"),
        content: Form(
          key: formKey,
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                TextFormField(
                  controller: nameController,
                  decoration: InputDecoration(
                      labelText: "Section Name (e.g., Main Roof)"),
                  validator: (value) => (value == null || value.isEmpty)
                      ? "Name is required"
                      : null,
                ),
                SizedBox(height: 10),
                TextFormField(
                  controller: lengthController,
                  decoration:
                      InputDecoration(labelText: "Roof Length (meters)"),
                  keyboardType: TextInputType.numberWithOptions(decimal: true),
                  validator: (value) {
                    if (value == null || value.isEmpty)
                      return "Length is required";
                    final val = double.tryParse(value);
                    if (val == null || val <= 0)
                      return "Enter a valid positive length";
                    return null;
                  },
                ),
                SizedBox(height: 10),
                TextFormField(
                  controller: widthController,
                  decoration: InputDecoration(labelText: "Roof Width (meters)"),
                  keyboardType: TextInputType.numberWithOptions(decimal: true),
                  validator: (value) {
                    if (value == null || value.isEmpty)
                      return "Width is required";
                    final val = double.tryParse(value);
                    if (val == null || val <= 0)
                      return "Enter a valid positive width";
                    return null;
                  },
                ),
              ],
            ),
          ),
        ),
        actions: <Widget>[
          TextButton(
              onPressed: () => Navigator.of(dialogContext).pop(),
              child: Text("Cancel")),
          ElevatedButton(
            onPressed: () async {
              if (formKey.currentState!.validate()) {
                final newId = uuid.v4();
                final newSection = RooftopSection(
                  id: newId,
                  name: nameController.text.trim(),
                  roofLengthM: double.parse(lengthController.text),
                  roofWidthM: double.parse(widthController.text),
                );
                try {
                  await _dbRef.child(newId).set(newSection.toJson());
                  if (mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                      content: Text("${newSection.name} added!"),
                      backgroundColor: Colors.green,
                    ));
                    Navigator.of(dialogContext).pop();
                    setState(() {
                      _selectedRooftopId = newId;
                    }); // Auto-select new section
                  }
                } catch (e) {
                  if (mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                      content: Text("Failed to add section: $e"),
                      backgroundColor: Colors.red,
                    ));
                  }
                }
              }
            },
            child: Text("Add Section"),
          ),
        ],
      ),
    );
  }

  void _deleteRooftopSection(String rooftopId, String rooftopName) {
    showDialog(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: Text("Confirm Delete"),
        content: Text(
            "Are you sure you want to delete '$rooftopName' and all its panels? This action cannot be undone."),
        actions: <Widget>[
          TextButton(
              onPressed: () => Navigator.of(dialogContext).pop(),
              child: Text("Cancel")),
          TextButton(
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            onPressed: () async {
              try {
                await _dbRef.child(rooftopId).remove();
                if (mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                    content: Text("Rooftop section '$rooftopName' deleted."),
                    backgroundColor: Colors.orange,
                  ));
                  Navigator.of(dialogContext).pop();
                  // _selectedRooftopId will be handled by the listener if it was the deleted one.
                }
              } catch (e) {
                if (mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                    content: Text("Failed to delete section: $e"),
                    backgroundColor: Colors.red,
                  ));
                }
              }
            },
            child: Text("Delete"),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    RooftopSection? currentRooftop = (_selectedRooftopId != null &&
            _rooftopSections.containsKey(_selectedRooftopId))
        ? _rooftopSections[_selectedRooftopId!]
        : null;

    return Scaffold(
      appBar: AppBar(
        title: Text("Solar Panel Configuration"),
        actions: [
          IconButton(
            icon: Icon(Icons.add_circle_outline),
            tooltip: "Add Rooftop Section",
            onPressed: _addRooftopSectionDialog,
          ),
        ],
      ),
      body: Column(
        children: [
          if (_rooftopSections.isNotEmpty)
            Padding(
              padding: const EdgeInsets.all(12.0),
              child: DropdownButtonFormField<String>(
                decoration: InputDecoration(
                  labelText: "Select Rooftop Section",
                  contentPadding:
                      EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                ),
                value: _selectedRooftopId,
                items: _rooftopSections.entries.map((entry) {
                  return DropdownMenuItem<String>(
                    value: entry.key,
                    child:
                        Text(entry.value.name, overflow: TextOverflow.ellipsis),
                  );
                }).toList(),
                onChanged: (String? newValue) {
                  setState(() {
                    _selectedRooftopId = newValue;
                  });
                },
                isExpanded: true,
              ),
            ),
          if (_rooftopSections.isEmpty)
            Expanded(
              child: Center(
                  child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Text(
                    "No rooftop sections defined.\nClick '+' in the app bar to add one.",
                    textAlign: TextAlign.center,
                    style: TextStyle(fontSize: 16, color: Colors.grey[600])),
              )),
            ),
          if (currentRooftop != null)
            Expanded(
              child: SingleChildScrollView(
                padding: EdgeInsets.fromLTRB(16.0, 0, 16.0, 16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildRooftopInfoCard(currentRooftop),
                    SizedBox(height: 16),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text("Solar Panels",
                            style: Theme.of(context).textTheme.titleLarge),
                        ElevatedButton.icon(
                          icon: Icon(Icons.solar_power_outlined),
                          label: Text("Add Panel"),
                          onPressed: () => _addPanelDialog(currentRooftop),
                        ),
                      ],
                    ),
                    SizedBox(height: 10),
                    _buildPanelList(currentRooftop),
                  ],
                ),
              ),
            )
          else if (_rooftopSections.isNotEmpty && _selectedRooftopId == null)
            Expanded(
              child: Center(
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: Text(
                      "Please select a rooftop section from the dropdown above.",
                      textAlign: TextAlign.center,
                      style: TextStyle(fontSize: 16, color: Colors.grey[700])),
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildRooftopInfoCard(RooftopSection rooftop) {
    return Card(
      elevation: 2,
      margin: EdgeInsets.symmetric(vertical: 8),
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Expanded(
                    child: Text(rooftop.name,
                        style: Theme.of(context).textTheme.headlineSmall,
                        overflow: TextOverflow.ellipsis)),
                IconButton(
                  icon: Icon(Icons.delete_sweep_outlined,
                      color: Colors.redAccent),
                  tooltip: "Delete '${rooftop.name}' Section",
                  onPressed: () =>
                      _deleteRooftopSection(rooftop.id, rooftop.name),
                )
              ],
            ),
            SizedBox(height: 12),
            _infoRow("Dimensions:",
                "${rooftop.roofLengthM.toStringAsFixed(1)}m x ${rooftop.roofWidthM.toStringAsFixed(1)}m"),
            _infoRow(
                "Total Area:", "${rooftop.totalAreaM2.toStringAsFixed(2)} m²"),
            _infoRow(
                "Area Used:", "${rooftop.usedAreaM2.toStringAsFixed(2)} m²",
                color: Colors.orange.shade700),
            _infoRow("Remaining Area:",
                "${rooftop.remainingAreaM2.toStringAsFixed(2)} m²",
                color: Colors.green.shade700, isBold: true),
            Divider(height: 20, thickness: 0.5),
            _infoRow("Total Wattage:", "${rooftop.totalWattageW} W"),
            _infoRow("Active Wattage:", "${rooftop.activeWattageW} W",
                color: Colors.blue.shade700, isBold: true),
          ],
        ),
      ),
    );
  }

  Widget _infoRow(String label, String value,
      {Color? color, bool isBold = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 3.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: TextStyle(color: Colors.grey[700])),
          Text(
            value,
            style: TextStyle(
              fontWeight: isBold ? FontWeight.bold : FontWeight.normal,
              color: color ?? Theme.of(context).textTheme.bodyLarge?.color,
              fontSize: isBold ? 15 : 14,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPanelList(RooftopSection rooftop) {
    if (rooftop.panels.isEmpty) {
      return Padding(
        padding: const EdgeInsets.symmetric(vertical: 20.0),
        child: Center(
            child: Text("No panels added to this section yet.",
                style: TextStyle(color: Colors.grey[600]))),
      );
    }
    return ListView.builder(
      shrinkWrap: true,
      physics: NeverScrollableScrollPhysics(),
      itemCount: rooftop.panels.length,
      itemBuilder: (context, index) {
        final panelId = rooftop.panels.keys.elementAt(index);
        final panel = rooftop.panels[panelId]!;
        return Card(
          elevation: 1.5,
          margin: EdgeInsets.symmetric(vertical: 5),
          child: ListTile(
            leading: Icon(
                panel.isFaulty
                    ? Icons.warning_amber_rounded
                    : Icons.solar_power_rounded,
                color: panel.isFaulty
                    ? Colors.orangeAccent
                    : Colors.amber.shade700,
                size: 30),
            title: Text("${panel.modelName} (${panel.wattageW}W)",
                style: TextStyle(fontWeight: FontWeight.w500)),
            subtitle: Text(
                "Size: ${panel.lengthM}m x ${panel.widthM}m (${panel.areaM2.toStringAsFixed(2)} m²)\nStatus: ${panel.isFaulty ? 'FAULTY' : 'Operational'}"),
            isThreeLine: true,
            trailing: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                IconButton(
                  icon: Icon(
                      panel.isFaulty
                          ? Icons.unpublished_outlined
                          : Icons.error_outline_rounded,
                      color: panel.isFaulty ? Colors.green : Colors.orange),
                  tooltip:
                      panel.isFaulty ? "Mark as Operational" : "Mark as Faulty",
                  onPressed: () => _togglePanelFaultyStatus(rooftop.id, panel),
                ),
                IconButton(
                  icon: Icon(Icons.delete_outline_rounded,
                      color: Colors.redAccent),
                  tooltip: "Remove Panel",
                  onPressed: () =>
                      _removePanel(rooftop.id, panel.id, panel.modelName),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  void _addPanelDialog(RooftopSection rooftop) {
    final modelController = TextEditingController();
    final lengthController = TextEditingController();
    final widthController = TextEditingController();
    final wattageController = TextEditingController();
    final formKey = GlobalKey<FormState>();

    showDialog(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: Text("Add Panel to ${rooftop.name}"),
        content: Form(
          key: formKey,
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                TextFormField(
                  controller: modelController,
                  decoration: InputDecoration(labelText: "Panel Model"),
                  validator: (v) => (v == null || v.isEmpty)
                      ? "Model name is required"
                      : null,
                ),
                SizedBox(height: 10),
                TextFormField(
                  controller: lengthController,
                  decoration: InputDecoration(labelText: "Panel Length (m)"),
                  keyboardType: TextInputType.numberWithOptions(decimal: true),
                  validator: (v) {
                    if (v == null || v.isEmpty) return "Length is required";
                    final val = double.tryParse(v);
                    if (val == null || val <= 0)
                      return "Enter a valid positive length";
                    return null;
                  },
                ),
                SizedBox(height: 10),
                TextFormField(
                  controller: widthController,
                  decoration: InputDecoration(labelText: "Panel Width (m)"),
                  keyboardType: TextInputType.numberWithOptions(decimal: true),
                  validator: (v) {
                    if (v == null || v.isEmpty) return "Width is required";
                    final val = double.tryParse(v);
                    if (val == null || val <= 0)
                      return "Enter a valid positive width";
                    return null;
                  },
                ),
                SizedBox(height: 10),
                TextFormField(
                  controller: wattageController,
                  decoration: InputDecoration(labelText: "Panel Wattage (W)"),
                  keyboardType: TextInputType.number,
                  validator: (v) {
                    if (v == null || v.isEmpty) return "Wattage is required";
                    final val = int.tryParse(v);
                    if (val == null || val <= 0)
                      return "Enter a valid positive wattage";
                    return null;
                  },
                ),
              ],
            ),
          ),
        ),
        actions: <Widget>[
          TextButton(
              onPressed: () => Navigator.of(dialogContext).pop(),
              child: Text("Cancel")),
          ElevatedButton(
            onPressed: () async {
              if (formKey.currentState!.validate()) {
                final panelLength = double.parse(lengthController.text);
                final panelWidth = double.parse(widthController.text);
                final panelArea = panelLength * panelWidth;

                if (panelArea > rooftop.remainingAreaM2 + 0.001) {
                  // Add small epsilon for float comparison
                  if (mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                          content: Text(
                              "Not enough space! Panel: ${panelArea.toStringAsFixed(2)}m², Available: ${rooftop.remainingAreaM2.toStringAsFixed(2)}m²"),
                          backgroundColor: Colors.red),
                    );
                  }
                  return;
                }

                final newPanelId = uuid.v4();
                final newPanel = SolarPanel(
                  id: newPanelId,
                  modelName: modelController.text.trim(),
                  lengthM: panelLength,
                  widthM: panelWidth,
                  wattageW: int.parse(wattageController.text),
                  addedTimestamp: DateTime.now(),
                );

                try {
                  await _dbRef
                      .child(rooftop.id)
                      .child('panels')
                      .child(newPanelId)
                      .set(newPanel.toJson());
                  if (mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                        content: Text("${newPanel.modelName} added!"),
                        backgroundColor: Colors.green));
                    Navigator.of(dialogContext).pop();
                  }
                } catch (e) {
                  if (mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                        content: Text("Failed to add panel: $e"),
                        backgroundColor: Colors.red));
                  }
                }
              }
            },
            child: Text("Add Panel"),
          ),
        ],
      ),
    );
  }

  void _removePanel(String rooftopId, String panelId, String panelName) {
    showDialog(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: Text("Confirm Remove Panel"),
        content: Text("Are you sure you want to remove '$panelName'?"),
        actions: <Widget>[
          TextButton(
              onPressed: () => Navigator.of(dialogContext).pop(),
              child: Text("Cancel")),
          TextButton(
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            onPressed: () async {
              try {
                await _dbRef
                    .child(rooftopId)
                    .child('panels')
                    .child(panelId)
                    .remove();
                if (mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                      content: Text("Panel '$panelName' removed."),
                      backgroundColor: Colors.orange));
                  Navigator.of(dialogContext).pop();
                }
              } catch (e) {
                if (mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                      content: Text("Failed to remove panel: $e"),
                      backgroundColor: Colors.red));
                }
              }
            },
            child: Text("Remove"),
          ),
        ],
      ),
    );
  }

  void _togglePanelFaultyStatus(String rooftopId, SolarPanel panel) async {
    final newFaultyStatus = !panel.isFaulty;
    try {
      await _dbRef
          .child(rooftopId)
          .child('panels')
          .child(panel.id)
          .child('isFaulty')
          .set(newFaultyStatus);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
              content: Text(
                  "${panel.modelName} marked as ${newFaultyStatus ? 'FAULTY' : 'Operational'}."),
              backgroundColor:
                  newFaultyStatus ? Colors.orangeAccent : Colors.lightGreen),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
            content: Text("Failed to update panel status: $e"),
            backgroundColor: Colors.red));
      }
    }
  }
}
