@echo off
setlocal enabledelayedexpansion

:: Define the base directory (lib)
set "BASE_DIR=lib"

:: Create base lib directory if it doesn't exist (Flutter usually does this)
if not exist "%BASE_DIR%" (
    echo Creating base directory: %BASE_DIR%
    mkdir "%BASE_DIR%"
)

:: --- Define Directories and Files ---
:: Format: path\to\directory:file1.dart,file2.dart;another\path:fileA.dart
:: Note the use of backslashes for paths in CMD and care with special characters.

set "MODULE_STRUCTURE="
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\simulation\controllers:simulation_controller.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\simulation\models:simulation_model.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\simulation\screens:simulation_screen.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\simulation\services:simulation_firebase_service.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\simulation\utils:simulation_calculator.dart,string_extensions.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\simulation\widgets:fault_indicator_widget.dart,interactive_roof_canvas.dart,panel_specification_selector.dart,panel_widget.dart,roof_designer_widget.dart,simulation_controls_panel.dart,simulation_results_view.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\maintenance\controllers:maintenance_controller.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\maintenance\models:maintenance_models.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\maintenance\screens:add_solar_panel_screen.dart,contact_directory_screen.dart,fault_detection_screen.dart,maintenance_home_screen.dart,repair_requests_screen.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\maintenance\services:maintenance_firebase_service.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\blockchain_trading\controllers:trading_controller.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\blockchain_trading\models:trading_models.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\blockchain_trading\posw:pose_calculator.dart,pose_model.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\blockchain_trading\screens:bidding_screen.dart,energy_trading_screen.dart,trade_negotiation_chat_screen.dart,trading_display_screen.dart,trading_home_screen.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\blockchain_trading\services:blockchain_service.dart,chat_service.dart,trading_firebase_service.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\solar_profile:apsl_sun_calc.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\solar_profile\src:constants.dart,date_utils.dart,moon_utils.dart,position_utils.dart,sun_utils.dart,time_utils.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\shared\auth:auth_service.dart,auth_wrapper.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\shared\theme:app_theme.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\shared\utils:location_service.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%\shared\widgets:custom_button.dart,custom_input_field.dart,loading_spinner.dart"
set "MODULE_STRUCTURE=!MODULE_STRUCTURE!;%BASE_DIR%:main.dart,firebase_options.dart"


echo Creating project structure based on definition...
echo Base directory: %BASE_DIR%
echo.

:: Remove the leading semicolon if it exists (from the way we build the string)
if "!MODULE_STRUCTURE:~0,1!"==";" set "MODULE_STRUCTURE=!MODULE_STRUCTURE:~1!"

for %%M in ("!MODULE_STRUCTURE:;=";"!") do (
    set "ENTRY=%%~M"
    for /f "tokens=1,* delims=:" %%A in ("!ENTRY!") do (
        set "DIR_PATH=%%A"
        set "FILES_LIST=%%B"

        :: Create directory if it doesn't exist
        if not exist "!DIR_PATH!" (
            echo Creating directory: !DIR_PATH!
            mkdir "!DIR_PATH!"
        ) else (
            echo Directory exists:  !DIR_PATH!
        )

        :: Create files if they don't exist
        set "CURRENT_FILES_LIST=!FILES_LIST!"
        setlocal enabledelayedexpansion
        for %%F in (!CURRENT_FILES_LIST:,^= ^!) do (
            endlocal
            set "FILE_NAME=%%F"
            set "FILE_PATH=!DIR_PATH!\!FILE_NAME!"
            if not exist "!FILE_PATH!" (
                echo   Creating file: !FILE_NAME! in !DIR_PATH!
                type NUL > "!FILE_PATH!"
            ) else (
                echo   File exists:   !FILE_NAME! in !DIR_PATH!
            )
            setlocal enabledelayedexpansion
        )
        endlocal
    )
)

echo.
echo Structure creation process complete.
echo Please manually verify 'lib\firebase_options.dart' (it should be generated by FlutterFire CLI).
echo Ensure 'lib\solar_profile\apsl_sun_calc.dart' and its 'src' contents are correctly populated.

endlocal
goto:eof